query myOrgRepos($queryString: String!) {
  search(query: $queryString, type: REPOSITORY, first: 2) {
    repositoryCount
    edges {
      node {
        ... on Repository {
          name
        }
      }
    }
  }
}