try: https://graphql.org/swapi-graphql
===========
query char($char: ID) {
  person(personID: $char) {
    name
    starshipConnection {
      totalCount
      edges {
        cursor
        node {
          name
        }
      }
    }
  }
}

query chars {
  allPeople {
    totalCount
    edges {
      cursor
      node {
        ... on Person {
          homeworld {
            name
          }
        }
        id
        name
      }
    }
  }
}


======

{
  "1": "luke",
  "2": "c-3po",
  "3": "r2",
  "4": "dark",
  "5": "leia",
  "20": "yoda",
  "solo": {
    "id": "cGVvcGxlOjE0",
    "name": "Han Solo"
  },
  "char": "cGVvcGxlOjE0"
}
