query($owner: String!, $lab: String!) {
  repository(
    owner: $owner, 
    name: $lab) {
    issues(last:2, states:OPEN) {
      edges {
        node {
          title
          url
          labels(first:5) {
            edges {
              node {
                name
              }
            }
          }
        }
      }
    }
  }
}
